### ISSUE TITLE
Support for STM8?

### ISSUE THREAD

**Issue by David-Gould** [omarandlorraine/strop#5]
The STM8 is a widely used embedded 8 bit mcu that is very much like an upgraded MC6800 or 6502. Please consider supporting it. Thanks!

**Comment by omarandlorraine** [comment]
It's a good idea. Because the STM8 has 16 bit registers, (X and Y are both 16 bits on the STM8) I will need to fix issue #4 first.

**Comment by David-Gould** [comment]
On Wed, 16 Mar 2022 09:16:15 -0700
omarandlorraine ***@***.***> wrote:

> Just to give you an update and some encouragement on this. There is now (very!) rudimentary STM8 support. It has a handful of opcodes and is generating (very!) simple programs. Has a little while to go before being actually useful.

Thanks, I am watching with interest.

-dg


-- 
David Gould                                   ***@***.***
Racism is so American, that if you protest racism, people
think you're protesting America.
